### PR TITLE
fixes #97

### LINKED ISSUE #97: [Bug] Chemeo Import failing
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
In some cases import of a component from Chemeo-DB is not working. If there is only a single component in database matching search criteria nothing is imported. 

**To Reproduce**
1. Go to Component creator utility
2. Click on Import component from Chemeo Databas
3. Enter "Ethanol" and search component
4. A list of several components is displayed. Ethanol may be selected an can be imported.
5. Enter "64-17-5", which is the CAS-number of ethanol
6. No list of components is displayed as only a single component is matching this criteria. Nothing can be imported.

**Expected behavior**
Data should be imported

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.3 Update 5]

**Additional context**

### PR DESCRIPTION
**Pull request by jfkonecn**
I used the API from chemeo. 
https://www.chemeo.com/api/v1/

I could add some automated unit tests to the PR if you want me to. 
Just let me know what library you prefer I use to create them.

Do you have any code standards I need to follow for PR's?

You might what to consider making the httpclient a singleton although it's probably not a huge problem.
according to the docs:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0
"HttpClient is intended to be instantiated once per application, rather than per-use. See Remarks"
and
"HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly."

### CODE REVIEW

**Comment by DanWBR** [comment]
@jfkonecn did you close the pull request? may I ask why?

**Comment by jfkonecn** [comment]
I wasn't sure if it would fix the bug. I can reactivate it if you'd like me to.

**Comment by jfkonecn** [comment]
After doing some more testing I think it's good.

Are the method calls for 
DWSIM/Forms/FormImportCompoundOnline.vb
and
DWSIM/Forms/Compound Creator/FormImportCompoundDataChemeo.vb
not used?

**Comment by DanWBR** [comment]
> After doing some more testing I think it's good.
> 
> Are the method calls for
> DWSIM/Forms/FormImportCompoundOnline.vb
> and
> DWSIM/Forms/Compound Creator/FormImportCompoundDataChemeo.vb
> not used?

Sorry, I didn't understand. If you're asking if there are chemeo calls beyond these two, I'm almost 100% that there isn't

**Comment by jfkonecn** [comment]
> > After doing some more testing I think it's good.
> > Are the method calls for
> > DWSIM/Forms/FormImportCompoundOnline.vb
> > and
> > DWSIM/Forms/Compound Creator/FormImportCompoundDataChemeo.vb
> > not used?
> 
> Sorry, I didn't understand. If you're asking if there are chemeo calls beyond these two, I'm almost 100% that there isn't

I'm asking if the code is reachable.

In FormImportCompoundDataChemeo the function ChemeoParser.GetCompoundIDs is called by btnNext_Click which is called by btnPrev_Click, but btnPrev_Click isn't called anywhere.

With FormImportCompoundOnline the function ChemeoParser.GetCompoundIDs is called by btnNext_Click which is called by tbSearchString_KeyDown, but tbSearchString_KeyDown isn't called anywhere.

CompoundCreatorWizard seems to be only class where the call to ChemeoParser.GetCompoundIDs is reachable.

**Comment by DanWBR** [comment]
You can right click on the function name and select "Find All References" to view callers.

**Comment by DanWBR** [comment]
I didn't do that for you already because I'm not using my computer right now.

**Comment by jfkonecn** [comment]
After doing that it still looks like the those two calls are unreachable.

I'm using the "windows" branch and I'm on the commit:
"Added translation file"
1888dce3934d8c7b1611de7e289e7598383a063d

**Comment by DanWBR** [comment]
in VB, the Handles keyword in the following command

`Private Sub btnNext_Click(sender As Object, e As EventArgs) Handles btnNext.Click`

means that it will be called when the btnNext Click event fires. btnNext is the "Next" button in the Compound Import wizard.

**Comment by DanWBR** [comment]
Thanks @jfkonecn, issue #97 is now fixed!

**Pull request merged**
